#!/bin/sh
# see http://vim-jp.org/blog/2015/10/15/tovim-on-shell-command-pipes.html

TOVIMTMP="`mktemp`"
trap 'rm $TOVIMTMP' ERR

cat > $TOVIMTMP
vim $TOVIMTMP < /dev/tty > /dev/tty
cat $TOVIMTMP
rm $TOVIMTMP
